apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.schemaregistry.name }}
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:{{.Release.Namespace}}:{{ .Values.schemaregistry.name }}"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
spec:
  clusterIP: None
  ports:
  - name: default
    protocol: TCP
    port: 42
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-{{.Release.Namespace}}-{{ .Values.schemaregistry.name }}