apiVersion: v1
kind: Service
metadata:
  name: mqtt-adapter-1
  annotations:
    field.cattle.io/targetWorkloadIds: '["deployment:{{.Release.Namespace}}:mqtt-adapter-1"]'
    workload.cattle.io/targetWorkloadIdNoop: "true"
    workload.cattle.io/workloadPortBased: "true"
spec:
  clusterIP: None
  ports:
  - name: default
    protocol: TCP
    port: 42
    targetPort: 42
  selector:
    workload.user.cattle.io/workloadselector: deployment-{{.Release.Namespace}}-mqtt-adapter-1