apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
data:
  nats.conf: |
    # maximum payload
    max_payload: 268435456
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  labels:
    app: nats
    workload.user.cattle.io/workloadselector: deployment-{{.Release.Namespace}}-nats
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
      workload.user.cattle.io/workloadselector: deployment-{{.Release.Namespace}}-nats
  template:
    metadata:
      labels:
        app: nats
        workload.user.cattle.io/workloadselector: deployment-{{.Release.Namespace}}-nats
    spec:
      containers:
      - name: nats
        image: "{{ .Values.nats.image.repository }}:{{ .Values.nats.image.tag }}"
        imagePullPolicy: {{ .Values.nats.image.pullPolicy }}
        volumeMounts:
          - mountPath: /etc/nats
            name: vol1
        args:
        - -c
        - /etc/nats/nats.conf
      volumes:
      - configMap:
          defaultMode: 256
          name: nats-config
          optional: false
        name: vol1