apiVersion: v1
kind: ConfigMap
metadata:
  name: email.tmpl
data:
  email.tmpl: |
    To: {{.To}}
    From: {{.From}}
    Subject: {{.Subject}}
    {{.Header}}
    You have initiated password reset.
    Follow the link below to reset password.
    {{.Content}}
    {{.Footer}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users
  labels:
    app: users
    workload.user.cattle.io/workloadselector: deployment-{{.Release.Namespace}}-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
      workload.user.cattle.io/workloadselector: deployment-{{.Release.Namespace}}-users
  template:
    metadata:
      labels:
        app: users
        workload.user.cattle.io/workloadselector: deployment-{{.Release.Namespace}}-users
    spec:
      containers:
      - name: users
        image: "{{ .Values.users.image.repository }}:{{ .Values.users.image.tag }}"
        imagePullPolicy: {{ .Values.users.image.pullPolicy }}
        env:
          - name: MF_AUTHN_URL
            value: authn:8181
          - name: MF_EMAIL_DRIVER
            value: smtp
          - name: MF_EMAIL_FROM_ADDRESS
            value: from@example.com
          - name: MF_EMAIL_FROM_NAME
            value: Example
          - name: MF_EMAIL_HOST
            value: smtp.mailtrap.io
          - name: MF_EMAIL_PASSWORD
            value: 2b0d302e775b1e
          - name: MF_EMAIL_PORT
            value: "2525"
          - name: MF_EMAIL_TEMPLATE
            value: email.tmpl
          - name: MF_EMAIL_USERNAME
            value: 18bf7f70705139
          - name: MF_JAEGER_URL
            value: jaeger:6831
          - name: MF_TOKEN_RESET_ENDPOINT
            value: /reset-request
          - name: MF_USERS_DB
            value: {{ .Values.databases.postgresql.db.users }}
          - name: MF_USERS_DB_HOST
            value: {{ .Values.databases.postgresql.ip }}
          - name: MF_USERS_DB_PASS
            value: {{ .Values.databases.postgresql.password }}
          - name: MF_USERS_DB_PORT
            value: {{ .Values.databases.postgresql.port | quote }}
          - name: MF_USERS_DB_USER
            value: {{ .Values.databases.postgresql.username }}
          - name: MF_USERS_HTTP_PORT
            value: "8180"
          - name: MF_USERS_LOG_LEVEL
            value: {{ .Values.users.logLevel }}
        volumeMounts:
          - mountPath: /email.tmpl
            name: vol1
      volumes:
        - configMap:
            defaultMode: 0755
            name: email.tmpl
            optional: false
          name: vol1